[package]
name = "dosh"
version = "0.1.0"
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.15.0"
starlark = { git = "https://github.com/facebookexperimental/starlark-rust", branch = "main" }
structopt = "0.3.25"
