[tool.poetry]
name = "dosh"
version = "0.1.0"
description = "Shell-independent command manager."
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
lupa = "^1.13"
colorlog = "^6.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-httpserver = "^1.0.4"
pyinstaller = "^5.3"
pylint = "^2.15.0"

[tool.poetry.scripts]
dosh = "app:main"

[tool.poe.tasks.build]
cmd = "bash scripts/build.sh"
help = "Build dosh"

[tool.poe.tasks.lint]
cmd = "pre-commit run --all-files"
help = "Check code quality"

[tool.poe.tasks.test]
cmd = "pytest -sk $name"
help = "Run tests"

[[tool.poe.tasks.test.args]]
name = "name"
positional = true
default = "test"
help = "Filter tests by $name"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
