[tool.poetry]
name = "dosh"
version = "0.1.0"
description = "Shell-independent command manager."
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
# DO NOT ADD ANY DEPENDENCY. PYTHON IS BATTERY-INCLUDED.

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
poethepoet = "^0.15.0"
pytest-httpserver = "^1.0.4"
pyinstaller = "^5.3"

[tool.poetry.scripts]
dosh = "dosh.cli:run"

[tool.poe.tasks.build]
cmd = "poetry run pyinstaller dosh.py"
help = "Build dosh"

[tool.poe.tasks.lint]
cmd = "pre-commit run --all-files"
help = "Check code quality"

[tool.poe.tasks.test]
cmd = "pytest -sk $name"
help = "Run tests"

[[tool.poe.tasks.test.args]]
name = "name"
positional = true
default = "test"
help = "Filter tests by $name"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
