[tool.poetry]
name = "dosh"
version = "0.1.0"
description = "Shell-independent task manager."
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
lupa = "^1.13"
colorlog = "^6.7.0"
poetry = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
pytest-httpserver = "^1.0.4"
pyinstaller = "^5.7.0"
pylint = "^2.15.0"

[tool.poetry.scripts]
dosh = "app:main"

[tool.poe.tasks.build]
cmd = "poetry run pyinstaller app.py --name=dosh --console --noconfirm"
help = "Build dosh with pyinstaller"

[tool.poe.tasks.lint]
cmd = "pre-commit run --all-files"
help = "Check code quality"

[tool.poe.tasks.test]
cmd = "pytest -sk $name"
help = "Run tests"

[[tool.poe.tasks.test.args]]
name = "name"
positional = true
default = "test"
help = "Filter tests by $name"

[tool.pytest.ini_options]
addopts = "--cov=dosh --cov-report term-missing --cov-report html:./tests/cov_html"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
