version: 2.1

orbs:
  windows: circleci/windows@4.1.1

jobs:
  build-linux-amd64:
    machine:
      image: ubuntu-2204:2022.04.2

    steps:
      - checkout
      - run:
          name: "Download pyoxidizer"
          command: |
            curl -OL $URL/$VERSION/pyoxidizer-$VERSION-x86_64-unknown-linux-musl.tar.gz
            tar -xf pyoxidizer-$VERSION-x86_64-unknown-linux-musl.tar.gz
            mkdir -p /tmp/bin
            mv pyoxidizer-$VERSION-x86_64-unknown-linux-musl/pyoxidizer /tmp/bin
            export PATH=/tmp/bin:$PATH
          environment:
            VERSION: 0.22.0
            URL: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer
      - run:
          name: "Build dosh"
          command: "pyoxidizer build"
      - store_artifacts:
          path: /tmp/bin/pyoxidizer

  build-macos-amd64:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, MacOS!"

  build-windows-amd64:
    executor: windows/server-2022

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, Windows!"

workflows:
  build-all:
    jobs:
      - build-linux-amd64
      # - build-macos-amd64
      # - build-windows-amd64
