version: 2.1

orbs:
  python: circleci/python@2.0.3
  windows: circleci/windows@4.1.1
  pre-commit: oandacorp/pre-commit@0.8.0

commands:
  build:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run build

jobs:
  build-for-linux:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - build

  build-for-macos:
    macos:
      xcode: 12.5.1

    steps:
      - build

  build-for-windows:
    executor: windows/server-2022

    steps:
      - build

  release:
    executor: ...
    steps:
      - todo

workflows:
  pr-checks:
    jobs:
      - pre-commit/run:
          all-files: true
          use-cache: true

      - python/test:
          matrix:
            parameters:
              version: ["3.8", "3.9", "3.10"]

  main:
    jobs:
      - build
      - approve
      - release
