version: 2.1

orbs:
  python: circleci/python@2

filters-development: &filters-development
  branches:
    ignore: main

jobs:
  lint:
    executor:
      name: "python/default"
      tag: "3.9"

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: "poetry"
          args: "--no-ansi"

      - run: poetry run pip install pre-commit

      - run:
          name: "Create a temporary file for getting a cache key"
          command: |
            cp .pre-commit-config.yaml /tmp/checksum.txt
            poetry run python --version >> /tmp/checksum.txt

      - restore_cache:
          key: pre-commit-{{ checksum "/tmp/checksum.txt" }}

      - run: poetry run pre-commit run --all-files

      - save_cache:
          key: pre-commit-{{ checksum "/tmp/checksum.txt" }}
          paths:
            - ~/.cache/pre-commit

  test:
    parameters:
      version:
        type: string

    executor:
      name: "python/default"
      tag: << parameters.version >>

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: "poetry"
          args: "--no-ansi"

      - run: poetry run pytest

workflows:
  pr-checks:
    jobs:
      - lint:
          filters: *filters-development

      - test:
          matrix:
            parameters:
              version: ["3.8", "3.9", "3.10", "3.11"]
          filters: *filters-development
