version: 2.1

orbs:
  windows: circleci/windows@4.1.1

jobs:
  build-linux-amd64:
    machine:
      image: ubuntu-2204:2022.04.2

    steps:
      - checkout
      - run:
          name: "Download pyoxidizer"
          command: |
            curl -OL $URL
            tar -xf $NAME.tar.gz
            mkdir -p /tmp/bin
            mv $NAME/pyoxidizer /tmp/bin
          environment:
            VERSION: 0.22.0
            NAME: pyoxidizer-$VERSION-x86_64-unknown-linux-musl
            URL: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer/$VERSION/$NAME.tar.gz
      - run:
          name: "Say hello"
          command: "echo Hello, Ubuntu!"
      - store_artifacts:
          path: /tmp/bin/pyoxidizer

  build-macos-amd64:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, MacOS!"

  build-windows-amd64:
    executor: windows/server-2022

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, Windows!"

workflows:
  build-all:
    jobs:
      - build-linux-amd64
      # - build-macos-amd64
      # - build-windows-amd64
