version: 2.1

orbs:
  python: circleci/python@2.0.3
  windows: circleci/windows@4.1.1

commands:
  lint-and-test:
    steps:
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run poe lint
      - run: poetry run poe test

jobs:
  lint-linux-amd64:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - checkout
      - lint-and-test

  lint-macos-amd64:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - lint-and-test

  lint-windows-amd64:
    executor: windows/server-2022

    steps:
      - checkout
      - lint-and-test

workflows:
  lint-and-test-all:
    jobs:
      - lint-linux-amd64
      - lint-macos-amd64
      - lint-windows-amd64
