version: 2.1

orbs:
  python: circleci/python@2.0.3
  windows: circleci/windows@4.1.1

jobs:
  build-linux-amd64:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run poe test
      - run:
          name: Build with pyoxidizer
          command: poetry run poe build

  build-macos-amd64:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, MacOS!"

  build-windows-amd64:
    executor: windows/server-2022

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, Windows!"

workflows:
  build-all:
    jobs:
      - build-linux-amd64
      # - build-macos-amd64
      # - build-windows-amd64
