name: DOSH CLI Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v6.0.1
      with:
        enable-cache: true

    - name: Pre-commit
      run: uvx pre-commit run --all-files

    - name: Run tests
      run: uv run pytest --cov=. --cov-report term-missing --cov-report html:./tests/cov_html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: tests/cov_html

  build-on-linux:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Package DOSH CLI for Linux
        run: ./package.sh

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-cli-linux
          path: dosh-cli-linux

  # build-on-macos:
  #   needs: pre-checks
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Package DOSH CLI for MacOS
  #       run: ./package.sh

  #     - name: Archive package
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: dosh-cli-macos
  #         path: dosh-cli-*

  # build-on-windows:
  #   needs: pre-checks
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Package DOSH CLI for Windows
  #       run: ./package.sh
  #       shell: bash

  #     - name: Archive package
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: dosh-cli-windows
  #         path: dosh-cli-*
