name: DOSH Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Build release distributions
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  package-on-linux-arm64:
    runs-on: ubuntu-24.04-arm

    needs:
      - build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - uses: ./actions/package-dosh
        with:
          dosh-binary-name: dosh-linux-arm64
          dist-path: dist
          output-path: bin

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-linux-arm64
          path: bin

  package-on-linux-x86_64:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - uses: ./actions/package-dosh
        with:
          dosh-binary-name: dosh-linux-x86_64
          dist-path: dist
          output-path: bin

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-linux-x86_64
          path: bin

  package-on-macos:
    runs-on: macos-latest

    needs:
      - build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - uses: ./actions/package-dosh
        with:
          dosh-binary-name: dosh-macos
          dist-path: dist
          output-path: bin

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-macos
          path: bin

  package-on-windows:
    runs-on: windows-latest

    needs:
      - build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - uses: ./actions/package-dosh
        with:
          dosh-binary-name: dosh-windows-x86_64
          dist-path: dist
          output-path: bin

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-windows-x86_64
          path: bin

  release:
    runs-on: ubuntu-latest

    needs:
      - build
      - package-on-linux-arm64
      - package-on-linux-x86_64
      - package-on-macos
      - package-on-windows

    permissions:
      contents: write

    steps:
      - name: Retrieve packages and distributions
        uses: actions/download-artifact@v4

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dosh-*/dosh-*,release-dists/*"
