name: DOSH Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Build release distributions
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - build

    permissions:
      id-token: write

    environment:
      name: release
      url: https://pypi.org/p/dosh-cli

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  build-on-linux:
    runs-on: ubuntu-latest

    needs:
      - pypi-publish

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Package DOSH CLI for Linux
        run: ./package.sh
        env:
          DOSH_BINARY_NAME: dosh-cli-linux

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-cli-linux
          path: bin

  build-on-macos:
    runs-on: macos-latest

    needs:
      - pypi-publish

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Package DOSH CLI for MacOS
        run: ./package.sh
        env:
          DOSH_BINARY_NAME: dosh-cli-macos

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-cli-macos
          path: bin

  build-on-windows:
    runs-on: windows-latest

    needs:
      - pypi-publish

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Package DOSH CLI for Windows
        run: ./package.sh
        shell: bash
        env:
          DOSH_BINARY_NAME: dosh-cli-windows

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: dosh-cli-windows
          path: bin
